services:
  wireguard:
    build: .
    ports: 
      - 10086:10086
      - 51820:51820/udp
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - run:/wgd/run
      - ./wireguard-config:/etc/wireguard/

volumes:
  run:
