[Interface]
PrivateKey =
SaveConfig = true
Address = 10.0.0.1/24
ListenPort = 51820

PostUp = nft add table ip nat; nft add chain ip nat POSTROUTING "{ type nat hook postrouting priority srcnat; policy accept; }"; nft add rule ip nat POSTROUTING oifname "eth0" masquerade
PostDown = nft delete table ip nat
